import "./globals.css";
// eslint-disable-next-line camelcase
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

// eslint-disable-next-line new-cap
const geistSans = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans"
});

// eslint-disable-next-line new-cap
const geistMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-geist-mono"
});

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				{children}
			</body>
		</html>
	);
}
