name: Lint

on:
  pull_request:
    types:
      - opened
      - edited
  push:

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check-Out Repository
        uses: actions/checkout@v4
      - name: Set Up Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
